<?php

namespace Database\Seeders;

use App\Models\Bitgo;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BitgoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $coins = [
            [
                'wallet_id' => 'btc-wallet-1',
                'wallet_name' => 'Bitcoin',
                'wallet_ticker' => 'BTC',
                'type' => 'bitcoin',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/1.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'eth-wallet-1',
                'wallet_name' => 'Ethereum',
                'wallet_ticker' => 'ETH',
                'type' => 'ethereum',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'usdt-wallet-1',
                'wallet_name' => 'Tether (USDT)',
                'wallet_ticker' => 'USDT',
                'type' => 'tether',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/825.png',
                'meta_data' => (['network' => 'trc20']),
            ],
            [
                'wallet_id' => 'xrp-wallet-1',
                'wallet_name' => 'Ripple (XRP)',
                'wallet_ticker' => 'XRP',
                'type' => 'ripple',
                'require_memo' => true,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/52.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'ltc-wallet-1',
                'wallet_name' => 'Litecoin',
                'wallet_ticker' => 'LTC',
                'type' => 'litecoin',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/2.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'dash-wallet-1',
                'wallet_name' => 'Dash',
                'wallet_ticker' => 'DASH',
                'type' => 'dash',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/131.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'zcash-wallet-1',
                'wallet_name' => 'Zcash',
                'wallet_ticker' => 'ZEC',
                'type' => 'zcash',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/1437.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'btg-wallet-1',
                'wallet_name' => 'Bitcoin Gold',
                'wallet_ticker' => 'BTG',
                'type' => 'bitcoin-gold',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/2083.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'bch-wallet-1',
                'wallet_name' => 'Bitcoin Cash',
                'wallet_ticker' => 'BCH',
                'type' => 'bitcoin-cash',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/1831.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'doge-wallet-1',
                'wallet_name' => 'Dogecoin',
                'wallet_ticker' => 'DOGE',
                'type' => 'dogecoin',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/74.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'trx-wallet-1',
                'wallet_name' => 'Tron',
                'wallet_ticker' => 'TRX',
                'type' => 'tron',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/1958.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'eos-wallet-1',
                'wallet_name' => 'EOS',
                'wallet_ticker' => 'EOS',
                'type' => 'eos',
                'require_memo' => true,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/1765.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'ada-wallet-1',
                'wallet_name' => 'Cardano',
                'wallet_ticker' => 'ADA',
                'type' => 'cardano',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/2010.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'xlm-wallet-1',
                'wallet_name' => 'Stellar',
                'wallet_ticker' => 'XLM',
                'type' => 'stellar',
                'require_memo' => true,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/512.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'xtz-wallet-1',
                'wallet_name' => 'Tezos',
                'wallet_ticker' => 'XTZ',
                'type' => 'tezos',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/2011.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'dot-wallet-1',
                'wallet_name' => 'Polkadot',
                'wallet_ticker' => 'DOT',
                'type' => 'polkadot',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/6636.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'sol-wallet-1',
                'wallet_name' => 'Solana',
                'wallet_ticker' => 'SOL',
                'type' => 'solana',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
            [
                'wallet_id' => 'usdc-wallet-1',
                'wallet_name' => 'USD Coin (USDC)',
                'wallet_ticker' => 'USDC',
                'type' => 'usdc',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png',
                'meta_data' => (['network' => 'erc20']),
            ],
            [
                'wallet_id' => 'shib-wallet-1',
                'wallet_name' => 'Shiba Inu',
                'wallet_ticker' => 'SHIB',
                'type' => 'shiba',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/5994.png',
                'meta_data' => (['network' => 'erc20']),
            ],
            [
                'wallet_id' => 'avax-wallet-1',
                'wallet_name' => 'Avalanche',
                'wallet_ticker' => 'AVAX',
                'type' => 'avalanche',
                'require_memo' => false,
                'can_deposit' => true,
                'can_payout' => true,
                'coin_logo' => 'https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png',
                'meta_data' => (['network' => 'mainnet']),
            ],
        ];

        foreach ($coins as $coin) {
            Bitgo::firstOrCreate([
                "wallet_name" => $coin['wallet_name'],
                "wallet_ticker" => $coin['wallet_ticker'],
            ],
            $coin);
        }
    }
}
