<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeds `assets` rows for Brokeret's tradable catalog — base_url/ui's
 * independent live-price pipeline (see BrokeretFeedService,
 * StreamBrokeretFeed), which has no fixed/enumerable symbol list anywhere
 * in this app's own config (it streams whatever Brokeret sends). This list
 * is a snapshot of every distinct symbol actually observed streaming in
 * production, captured from the brokeret:latest:* Redis keys
 * BrokeretFeedService::updateLatest() writes — real data, not guessed.
 *
 * Deliberately insertOrIgnore(), never delete() first (unlike AssetSeeder's
 * iqcent-scoped wipe+reseed) — this must never disturb a row an admin has
 * edited (e.g. flipped is_active) or one BrokeretFeedService has already
 * auto-registered live. Re-running this is just "make sure every symbol in
 * this snapshot has a row"; it does not prune anything.
 *
 * New symbols Brokeret starts streaming after this snapshot was taken don't
 * need a seeder update to become tradable — BrokeretFeedService registers
 * those itself the moment they're first seen (see its
 * ensureAssetRegistered()). This seeder just means the catalog doesn't
 * start empty and wait for live traffic to populate the admin panel.
 */
class BrokeretAssetSeeder extends Seeder
{
    /** Matches BrokeretFeedService::DEFAULT_PROFIT_MARGIN. */
    private const DEFAULT_PROFIT_MARGIN = 0.85;

    public function run(): void
    {
        $symbols = [
            ["symbol" => "AAVEUSD", "category" => "CRYPTO"],
            ["symbol" => "ADAEUR", "category" => "CRYPTO"],
            ["symbol" => "ADAUSD", "category" => "CRYPTO"],
            ["symbol" => "ALGOUSD", "category" => "CRYPTO"],
            ["symbol" => "APTUSD", "category" => "CRYPTO"],
            ["symbol" => "ARBUSD", "category" => "CRYPTO"],
            ["symbol" => "ATOMUSD", "category" => "CRYPTO"],
            ["symbol" => "AUDBRL", "category" => "EXOTICS"],
            ["symbol" => "AUDCAD", "category" => "MINORS"],
            ["symbol" => "AUDCHF", "category" => "MINORS"],
            ["symbol" => "AUDCNH", "category" => "EXOTICS"],
            ["symbol" => "AUDCZK", "category" => "EXOTICS"],
            ["symbol" => "AUDDKK", "category" => "EXOTICS"],
            ["symbol" => "AUDEUR", "category" => "MINORS"],
            ["symbol" => "AUDGBP", "category" => "MINORS"],
            ["symbol" => "AUDHKD", "category" => "EXOTICS"],
            ["symbol" => "AUDHUF", "category" => "EXOTICS"],
            ["symbol" => "AUDIDR", "category" => "EXOTICS"],
            ["symbol" => "AUDILS", "category" => "EXOTICS"],
            ["symbol" => "AUDINR", "category" => "EXOTICS"],
            ["symbol" => "AUDJPY", "category" => "MINORS"],
            ["symbol" => "AUDKRW", "category" => "EXOTICS"],
            ["symbol" => "AUDMXN", "category" => "EXOTICS"],
            ["symbol" => "AUDMYR", "category" => "EXOTICS"],
            ["symbol" => "AUDNOK", "category" => "EXOTICS"],
            ["symbol" => "AUDNZD", "category" => "MINORS"],
            ["symbol" => "AUDPLN", "category" => "EXOTICS"],
            ["symbol" => "AUDSEK", "category" => "EXOTICS"],
            ["symbol" => "AUDSGD", "category" => "EXOTICS"],
            ["symbol" => "AUDTHB", "category" => "EXOTICS"],
            ["symbol" => "AUDTRY", "category" => "EXOTICS"],
            ["symbol" => "AUDTWD", "category" => "EXOTICS"],
            ["symbol" => "AUDUSD", "category" => "MAJORS"],
            ["symbol" => "AUDZAR", "category" => "EXOTICS"],
            ["symbol" => "AVAXUSD", "category" => "CRYPTO"],
            ["symbol" => "AXSUSD", "category" => "CRYPTO"],
            ["symbol" => "BCHUSD", "category" => "CRYPTO"],
            ["symbol" => "BNBBTC", "category" => "CRYPTO"],
            ["symbol" => "BNBEUR", "category" => "CRYPTO"],
            ["symbol" => "BNBUSD", "category" => "CRYPTO"],
            ["symbol" => "BONKUSD", "category" => "CRYPTO"],
            ["symbol" => "BTCEUR", "category" => "CRYPTO"],
            ["symbol" => "BTCUSD", "category" => "CRYPTO"],
            ["symbol" => "CADCHF", "category" => "MINORS"],
            ["symbol" => "CADDKK", "category" => "EXOTICS"],
            ["symbol" => "CADEUR", "category" => "MINORS"],
            ["symbol" => "CADGBP", "category" => "MINORS"],
            ["symbol" => "CADHKD", "category" => "EXOTICS"],
            ["symbol" => "CADILS", "category" => "EXOTICS"],
            ["symbol" => "CADINR", "category" => "EXOTICS"],
            ["symbol" => "CADJPY", "category" => "MINORS"],
            ["symbol" => "CADMXN", "category" => "EXOTICS"],
            ["symbol" => "CADNOK", "category" => "EXOTICS"],
            ["symbol" => "CADPLN", "category" => "EXOTICS"],
            ["symbol" => "CADSEK", "category" => "EXOTICS"],
            ["symbol" => "CADSGD", "category" => "EXOTICS"],
            ["symbol" => "CADTRY", "category" => "EXOTICS"],
            ["symbol" => "CADZAR", "category" => "EXOTICS"],
            ["symbol" => "CHFCZK", "category" => "EXOTICS"],
            ["symbol" => "CHFDKK", "category" => "EXOTICS"],
            ["symbol" => "CHFEUR", "category" => "MINORS"],
            ["symbol" => "CHFGBP", "category" => "MINORS"],
            ["symbol" => "CHFHKD", "category" => "EXOTICS"],
            ["symbol" => "CHFHUF", "category" => "EXOTICS"],
            ["symbol" => "CHFINR", "category" => "EXOTICS"],
            ["symbol" => "CHFJPY", "category" => "MINORS"],
            ["symbol" => "CHFNOK", "category" => "EXOTICS"],
            ["symbol" => "CHFPLN", "category" => "EXOTICS"],
            ["symbol" => "CHFRUB", "category" => "EXOTICS"],
            ["symbol" => "CHFSEK", "category" => "EXOTICS"],
            ["symbol" => "CHFSGD", "category" => "EXOTICS"],
            ["symbol" => "CHFTHB", "category" => "EXOTICS"],
            ["symbol" => "CHFTRY", "category" => "EXOTICS"],
            ["symbol" => "CHFZAR", "category" => "EXOTICS"],
            ["symbol" => "CNHHKD", "category" => "EXOTICS"],
            ["symbol" => "CNHJPY", "category" => "EXOTICS"],
            ["symbol" => "COMPUSD", "category" => "CRYPTO"],
            ["symbol" => "CRVUSD", "category" => "CRYPTO"],
            ["symbol" => "CZKJPY", "category" => "EXOTICS"],
            ["symbol" => "DASHUSD", "category" => "CRYPTO"],
            ["symbol" => "DKKCHF", "category" => "EXOTICS"],
            ["symbol" => "DKKJPY", "category" => "EXOTICS"],
            ["symbol" => "DKKNOK", "category" => "EXOTICS"],
            ["symbol" => "DKKSEK", "category" => "EXOTICS"],
            ["symbol" => "DOGEUSD", "category" => "CRYPTO"],
            ["symbol" => "DOTUSD", "category" => "CRYPTO"],
            ["symbol" => "ENAUSD", "category" => "CRYPTO"],
            ["symbol" => "ENJUSD", "category" => "CRYPTO"],
            ["symbol" => "ETCUSD", "category" => "CRYPTO"],
            ["symbol" => "ETHBTC", "category" => "CRYPTO"],
            ["symbol" => "ETHEUR", "category" => "CRYPTO"],
            ["symbol" => "ETHUSD", "category" => "CRYPTO"],
            ["symbol" => "EURAED", "category" => "EXOTICS"],
            ["symbol" => "EURAUD", "category" => "MINORS"],
            ["symbol" => "EURBRL", "category" => "EXOTICS"],
            ["symbol" => "EURCAD", "category" => "MINORS"],
            ["symbol" => "EURCHF", "category" => "MINORS"],
            ["symbol" => "EURCNH", "category" => "EXOTICS"],
            ["symbol" => "EURCZK", "category" => "EXOTICS"],
            ["symbol" => "EURDKK", "category" => "EXOTICS"],
            ["symbol" => "EUREGP", "category" => "EXOTICS"],
            ["symbol" => "EURGBP", "category" => "MINORS"],
            ["symbol" => "EURHKD", "category" => "EXOTICS"],
            ["symbol" => "EURHUF", "category" => "EXOTICS"],
            ["symbol" => "EURIDR", "category" => "EXOTICS"],
            ["symbol" => "EURILS", "category" => "EXOTICS"],
            ["symbol" => "EURINR", "category" => "EXOTICS"],
            ["symbol" => "EURJPY", "category" => "MINORS"],
            ["symbol" => "EURKRW", "category" => "EXOTICS"],
            ["symbol" => "EURMXN", "category" => "EXOTICS"],
            ["symbol" => "EURMYR", "category" => "EXOTICS"],
            ["symbol" => "EURNOK", "category" => "EXOTICS"],
            ["symbol" => "EURNZD", "category" => "MINORS"],
            ["symbol" => "EURPHP", "category" => "EXOTICS"],
            ["symbol" => "EURPLN", "category" => "EXOTICS"],
            ["symbol" => "EURRON", "category" => "EXOTICS"],
            ["symbol" => "EURRUB", "category" => "EXOTICS"],
            ["symbol" => "EURSAR", "category" => "EXOTICS"],
            ["symbol" => "EURSEK", "category" => "EXOTICS"],
            ["symbol" => "EURSGD", "category" => "EXOTICS"],
            ["symbol" => "EURTHB", "category" => "EXOTICS"],
            ["symbol" => "EURTRY", "category" => "EXOTICS"],
            ["symbol" => "EURTWD", "category" => "EXOTICS"],
            ["symbol" => "EURUSD", "category" => "MAJORS"],
            ["symbol" => "EURZAR", "category" => "EXOTICS"],
            ["symbol" => "FETUSD", "category" => "CRYPTO"],
            ["symbol" => "FILUSD", "category" => "CRYPTO"],
            ["symbol" => "FLOKIUSD", "category" => "CRYPTO"],
            ["symbol" => "FLOWUSD", "category" => "CRYPTO"],
            ["symbol" => "GALAUSD", "category" => "CRYPTO"],
            ["symbol" => "GBPAED", "category" => "EXOTICS"],
            ["symbol" => "GBPAUD", "category" => "MINORS"],
            ["symbol" => "GBPBRL", "category" => "EXOTICS"],
            ["symbol" => "GBPCAD", "category" => "MINORS"],
            ["symbol" => "GBPCHF", "category" => "MINORS"],
            ["symbol" => "GBPCNH", "category" => "EXOTICS"],
            ["symbol" => "GBPCZK", "category" => "EXOTICS"],
            ["symbol" => "GBPDKK", "category" => "EXOTICS"],
            ["symbol" => "GBPEUR", "category" => "MINORS"],
            ["symbol" => "GBPHKD", "category" => "EXOTICS"],
            ["symbol" => "GBPHUF", "category" => "EXOTICS"],
            ["symbol" => "GBPIDR", "category" => "EXOTICS"],
            ["symbol" => "GBPILS", "category" => "EXOTICS"],
            ["symbol" => "GBPINR", "category" => "EXOTICS"],
            ["symbol" => "GBPJPY", "category" => "FOREX"],
            ["symbol" => "GBPKRW", "category" => "EXOTICS"],
            ["symbol" => "GBPMXN", "category" => "EXOTICS"],
            ["symbol" => "GBPMYR", "category" => "EXOTICS"],
            ["symbol" => "GBPNOK", "category" => "EXOTICS"],
            ["symbol" => "GBPNZD", "category" => "MINORS"],
            ["symbol" => "GBPPHP", "category" => "EXOTICS"],
            ["symbol" => "GBPPLN", "category" => "EXOTICS"],
            ["symbol" => "GBPRON", "category" => "EXOTICS"],
            ["symbol" => "GBPRUB", "category" => "EXOTICS"],
            ["symbol" => "GBPSAR", "category" => "EXOTICS"],
            ["symbol" => "GBPSEK", "category" => "EXOTICS"],
            ["symbol" => "GBPSGD", "category" => "EXOTICS"],
            ["symbol" => "GBPTHB", "category" => "EXOTICS"],
            ["symbol" => "GBPTRY", "category" => "EXOTICS"],
            ["symbol" => "GBPTWD", "category" => "EXOTICS"],
            ["symbol" => "GBPUSD", "category" => "MAJORS"],
            ["symbol" => "GBPZAR", "category" => "EXOTICS"],
            ["symbol" => "GRTUSD", "category" => "CRYPTO"],
            ["symbol" => "HBARUSD", "category" => "CRYPTO"],
            ["symbol" => "HKDJPY", "category" => "EXOTICS"],
            ["symbol" => "HUFCHF", "category" => "EXOTICS"],
            ["symbol" => "ICPUSD", "category" => "CRYPTO"],
            ["symbol" => "ILSJPY", "category" => "EXOTICS"],
            ["symbol" => "IMXUSD", "category" => "CRYPTO"],
            ["symbol" => "INJUSD", "category" => "CRYPTO"],
            ["symbol" => "INRJPY", "category" => "EXOTICS"],
            ["symbol" => "JPYAUD", "category" => "MINORS"],
            ["symbol" => "JPYBRL", "category" => "EXOTICS"],
            ["symbol" => "JPYCAD", "category" => "MINORS"],
            ["symbol" => "JPYCHF", "category" => "MINORS"],
            ["symbol" => "JPYCZK", "category" => "EXOTICS"],
            ["symbol" => "JPYDKK", "category" => "EXOTICS"],
            ["symbol" => "JPYEUR", "category" => "MINORS"],
            ["symbol" => "JPYGBP", "category" => "MINORS"],
            ["symbol" => "JPYHKD", "category" => "EXOTICS"],
            ["symbol" => "JPYIDR", "category" => "EXOTICS"],
            ["symbol" => "JPYILS", "category" => "EXOTICS"],
            ["symbol" => "JPYINR", "category" => "EXOTICS"],
            ["symbol" => "JPYKRW", "category" => "EXOTICS"],
            ["symbol" => "JPYMXN", "category" => "EXOTICS"],
            ["symbol" => "JPYMYR", "category" => "EXOTICS"],
            ["symbol" => "JPYNOK", "category" => "EXOTICS"],
            ["symbol" => "JPYNZD", "category" => "MINORS"],
            ["symbol" => "JPYPLN", "category" => "EXOTICS"],
            ["symbol" => "JPYRUB", "category" => "EXOTICS"],
            ["symbol" => "JPYSEK", "category" => "EXOTICS"],
            ["symbol" => "JPYTHB", "category" => "EXOTICS"],
            ["symbol" => "JPYTWD", "category" => "EXOTICS"],
            ["symbol" => "JPYZAR", "category" => "EXOTICS"],
            ["symbol" => "JUPUSD", "category" => "CRYPTO"],
            ["symbol" => "LDOUSD", "category" => "CRYPTO"],
            ["symbol" => "LINKUSD", "category" => "CRYPTO"],
            ["symbol" => "LTCBTC", "category" => "CRYPTO"],
            ["symbol" => "LTCEUR", "category" => "CRYPTO"],
            ["symbol" => "LTCUSD", "category" => "CRYPTO"],
            ["symbol" => "MANAUSD", "category" => "CRYPTO"],
            ["symbol" => "MXNJPY", "category" => "EXOTICS"],
            ["symbol" => "NEARUSD", "category" => "CRYPTO"],
            ["symbol" => "NEOUSD", "category" => "CRYPTO"],
            ["symbol" => "NOKCHF", "category" => "EXOTICS"],
            ["symbol" => "NOKDKK", "category" => "EXOTICS"],
            ["symbol" => "NOKJPY", "category" => "EXOTICS"],
            ["symbol" => "NOKSEK", "category" => "EXOTICS"],
            ["symbol" => "NZDAUD", "category" => "MINORS"],
            ["symbol" => "NZDCAD", "category" => "MINORS"],
            ["symbol" => "NZDCHF", "category" => "MINORS"],
            ["symbol" => "NZDDKK", "category" => "EXOTICS"],
            ["symbol" => "NZDEUR", "category" => "MINORS"],
            ["symbol" => "NZDGBP", "category" => "MINORS"],
            ["symbol" => "NZDJPY", "category" => "MINORS"],
            ["symbol" => "NZDNOK", "category" => "EXOTICS"],
            ["symbol" => "NZDSEK", "category" => "EXOTICS"],
            ["symbol" => "NZDSGD", "category" => "EXOTICS"],
            ["symbol" => "NZDTRY", "category" => "EXOTICS"],
            ["symbol" => "NZDUSD", "category" => "MAJORS"],
            ["symbol" => "NZDZAR", "category" => "EXOTICS"],
            ["symbol" => "ONDOUSD", "category" => "CRYPTO"],
            ["symbol" => "OPUSD", "category" => "CRYPTO"],
            ["symbol" => "PENGUUSD", "category" => "CRYPTO"],
            ["symbol" => "PEPEUSD", "category" => "CRYPTO"],
            ["symbol" => "PLNCHF", "category" => "EXOTICS"],
            ["symbol" => "PLNJPY", "category" => "EXOTICS"],
            ["symbol" => "QNTUSD", "category" => "CRYPTO"],
            ["symbol" => "RENDERUSD", "category" => "CRYPTO"],
            ["symbol" => "RUNEUSD", "category" => "CRYPTO"],
            ["symbol" => "SANDUSD", "category" => "CRYPTO"],
            ["symbol" => "SEIUSD", "category" => "CRYPTO"],
            ["symbol" => "SEKCHF", "category" => "EXOTICS"],
            ["symbol" => "SEKJPY", "category" => "EXOTICS"],
            ["symbol" => "SEKNOK", "category" => "EXOTICS"],
            ["symbol" => "SGDCHF", "category" => "EXOTICS"],
            ["symbol" => "SGDJPY", "category" => "EXOTICS"],
            ["symbol" => "SHIBUSD", "category" => "CRYPTO"],
            ["symbol" => "SNXUSD", "category" => "CRYPTO"],
            ["symbol" => "SOLBTC", "category" => "CRYPTO"],
            ["symbol" => "SOLEUR", "category" => "CRYPTO"],
            ["symbol" => "SOLUSD", "category" => "CRYPTO"],
            ["symbol" => "STXUSD", "category" => "CRYPTO"],
            ["symbol" => "SUIUSD", "category" => "CRYPTO"],
            ["symbol" => "TAOUSD", "category" => "CRYPTO"],
            ["symbol" => "THETAUSD", "category" => "CRYPTO"],
            ["symbol" => "TIAUSD", "category" => "CRYPTO"],
            ["symbol" => "TONUSD", "category" => "CRYPTO"],
            ["symbol" => "TRUMPUSD", "category" => "CRYPTO"],
            ["symbol" => "TRXUSD", "category" => "CRYPTO"],
            ["symbol" => "TRYCHF", "category" => "EXOTICS"],
            ["symbol" => "TRYJPY", "category" => "EXOTICS"],
            ["symbol" => "TRYZAR", "category" => "EXOTICS"],
            ["symbol" => "UNIUSD", "category" => "CRYPTO"],
            ["symbol" => "USDAED", "category" => "EXOTICS"],
            ["symbol" => "USDARS", "category" => "EXOTICS"],
            ["symbol" => "USDAUD", "category" => "MINORS"],
            ["symbol" => "USDBRL", "category" => "EXOTICS"],
            ["symbol" => "USDCAD", "category" => "MAJORS"],
            ["symbol" => "USDCHF", "category" => "MAJORS"],
            ["symbol" => "USDCLP", "category" => "EXOTICS"],
            ["symbol" => "USDCNH", "category" => "EXOTICS"],
            ["symbol" => "USDCOP", "category" => "EXOTICS"],
            ["symbol" => "USDCZK", "category" => "EXOTICS"],
            ["symbol" => "USDDKK", "category" => "EXOTICS"],
            ["symbol" => "USDEGP", "category" => "EXOTICS"],
            ["symbol" => "USDEUR", "category" => "MINORS"],
            ["symbol" => "USDGBP", "category" => "MINORS"],
            ["symbol" => "USDHKD", "category" => "EXOTICS"],
            ["symbol" => "USDHUF", "category" => "EXOTICS"],
            ["symbol" => "USDIDR", "category" => "EXOTICS"],
            ["symbol" => "USDILS", "category" => "EXOTICS"],
            ["symbol" => "USDINR", "category" => "EXOTICS"],
            ["symbol" => "USDISK", "category" => "EXOTICS"],
            ["symbol" => "USDJPY", "category" => "MAJORS"],
            ["symbol" => "USDKRW", "category" => "EXOTICS"],
            ["symbol" => "USDMXN", "category" => "EXOTICS"],
            ["symbol" => "USDMYR", "category" => "EXOTICS"],
            ["symbol" => "USDNOK", "category" => "EXOTICS"],
            ["symbol" => "USDNZD", "category" => "MINORS"],
            ["symbol" => "USDPEN", "category" => "EXOTICS"],
            ["symbol" => "USDPHP", "category" => "EXOTICS"],
            ["symbol" => "USDPKR", "category" => "EXOTICS"],
            ["symbol" => "USDPLN", "category" => "EXOTICS"],
            ["symbol" => "USDRON", "category" => "EXOTICS"],
            ["symbol" => "USDRUB", "category" => "EXOTICS"],
            ["symbol" => "USDSAR", "category" => "EXOTICS"],
            ["symbol" => "USDSEK", "category" => "EXOTICS"],
            ["symbol" => "USDSGD", "category" => "EXOTICS"],
            ["symbol" => "USDTHB", "category" => "EXOTICS"],
            ["symbol" => "USDTRY", "category" => "EXOTICS"],
            ["symbol" => "USDTWD", "category" => "EXOTICS"],
            ["symbol" => "USDVND", "category" => "EXOTICS"],
            ["symbol" => "USDZAR", "category" => "EXOTICS"],
            ["symbol" => "VETUSD", "category" => "CRYPTO"],
            ["symbol" => "VIRTUALUSD", "category" => "CRYPTO"],
            ["symbol" => "WIFUSD", "category" => "CRYPTO"],
            ["symbol" => "WLDUSD", "category" => "CRYPTO"],
            ["symbol" => "XAGAUD", "category" => "METALS"],
            ["symbol" => "XAGCAD", "category" => "METALS"],
            ["symbol" => "XAGEUR", "category" => "METALS"],
            ["symbol" => "XAGGBP", "category" => "METALS"],
            ["symbol" => "XAGINR", "category" => "METALS"],
            ["symbol" => "XAGJPY", "category" => "METALS"],
            ["symbol" => "XAGSAR", "category" => "METALS"],
            ["symbol" => "XAGTRY", "category" => "METALS"],
            ["symbol" => "XAGUSD", "category" => "METALS"],
            ["symbol" => "XAGZAR", "category" => "METALS"],
            ["symbol" => "XAUAUD", "category" => "METALS"],
            ["symbol" => "XAUCAD", "category" => "METALS"],
            ["symbol" => "XAUEUR", "category" => "METALS"],
            ["symbol" => "XAUGBP", "category" => "METALS"],
            ["symbol" => "XAUINR", "category" => "METALS"],
            ["symbol" => "XAUJPY", "category" => "METALS"],
            ["symbol" => "XAUSAR", "category" => "METALS"],
            ["symbol" => "XAUUSD", "category" => "METALS"],
            ["symbol" => "XAUZAR", "category" => "METALS"],
            ["symbol" => "XLMUSD", "category" => "CRYPTO"],
            ["symbol" => "XRPBTC", "category" => "CRYPTO"],
            ["symbol" => "XRPEUR", "category" => "CRYPTO"],
            ["symbol" => "XRPUSD", "category" => "CRYPTO"],
            ["symbol" => "XTZUSD", "category" => "CRYPTO"],
            ["symbol" => "ZARCHF", "category" => "EXOTICS"],
            ["symbol" => "ZARJPY", "category" => "EXOTICS"],
            ["symbol" => "ZECUSD", "category" => "CRYPTO"],
            ["symbol" => "ZILUSD", "category" => "CRYPTO"],
            ["symbol" => "ZROUSD", "category" => "CRYPTO"],
        ];

        foreach ($symbols as $entry) {
            DB::table('assets')->insertOrIgnore([
                'symbol' => $entry['symbol'],
                'name' => $entry['symbol'],
                'asset_group' => $entry['category'],
                'exchange_float' => 0,
                'asset_profit_margin' => self::DEFAULT_PROFIT_MARGIN,
                'is_otc' => false,
                'price_source' => 'brokeret',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
