stages:
  - deploy

deploy:
  stage: deploy
  script:
    - ssh user@203.161.63.75 <<EOF
      cd /var/www/polarisoption.io
      git pull origin main
      composer install --no-dev
      php artisan migrate --seed --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      EOF
