[program:iqcent-ws-relay]
command=/root/start_ws.sh
directory=/root
autostart=true
autorestart=true
startretries=10
startsecs=10
stopsignal=TERM
stopwaitsecs=15
user=root
redirect_stderr=true
stdout_logfile=/var/log/iqcent-ws-relay.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5