<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Syncs `assets` to the canonical Brokeret catalog supplied 2026-08-14 (326
 * symbols across Crypto/Majors/Minors/Exotics/Metals) — the same list
 * BrokeretAssetSeeder now seeds fresh installs from.
 *
 * Two things happen, both scoped to price_source='brokeret' plus the
 * (already-dark) 'iqcent' rows:
 *
 *  1. Every row whose symbol is NOT in the canonical list gets soft-deleted
 *     (Assets uses SoftDeletes) — this is all 158 iqcent-tagged rows (no
 *     collector has fed them since the iqcent pipeline was removed; see the
 *     price_source-in-admin-forms migration/commit around the same date)
 *     plus one stray Brokeret symbol, TONUSD, that isn't in the new list.
 *     Soft-delete, not a hard DELETE, so existing Trade/ExpressTrade rows
 *     that reference these symbols by string (no FK) keep working — this
 *     only removes them from the live, tradable catalog. It's also safe
 *     against BrokeretFeedService::ensureAssetRegistered() resurrecting
 *     TONUSD if Brokeret keeps streaming it: that call is a raw
 *     insertOrIgnore() against the unique `symbol` index, which still finds
 *     the (soft-deleted) row and skips re-inserting.
 *
 *  2. Every kept row gets its `name` and `asset_group` updated to the
 *     canonical values (proper display names instead of the bare symbol;
 *     uppercase category matching BrokeretFeedService's own
 *     strtoupper($category) convention) — this also fixes a pre-existing
 *     typo where GBPJPY was seeded with asset_group 'FOREX' instead of
 *     'MINORS'. is_active/price_source are reasserted to true/'brokeret' in
 *     case a row had drifted (e.g. an admin had deactivated it while
 *     iqcent was still the redundant duplicate for the same instrument).
 */
return new class extends Migration
{
    private const CATALOG = [
            ["symbol" => "AAVEUSD", "name" => "Aave / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "ADAEUR", "name" => "Cardano / Euro", "category" => "CRYPTO"],
            ["symbol" => "ADAUSD", "name" => "Cardano / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "ALGOUSD", "name" => "Algorand / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "APTUSD", "name" => "Aptos / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "ARBUSD", "name" => "Arbitrum / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "ATOMUSD", "name" => "Cosmos / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "AUDBRL", "name" => "Australian Dollar / Brazilian Real", "category" => "EXOTICS"],
            ["symbol" => "AUDCAD", "name" => "Australian Dollar / Canadian Dollar", "category" => "MINORS"],
            ["symbol" => "AUDCHF", "name" => "Australian Dollar / Swiss Franc", "category" => "MINORS"],
            ["symbol" => "AUDCNH", "name" => "Australian Dollar / Chinese Yuan (Offshore)", "category" => "EXOTICS"],
            ["symbol" => "AUDCZK", "name" => "Australian Dollar / Czech Koruna", "category" => "EXOTICS"],
            ["symbol" => "AUDDKK", "name" => "Australian Dollar / Danish Krone", "category" => "EXOTICS"],
            ["symbol" => "AUDEUR", "name" => "Australian Dollar / Euro", "category" => "MINORS"],
            ["symbol" => "AUDGBP", "name" => "Australian Dollar / British Pound", "category" => "MINORS"],
            ["symbol" => "AUDHKD", "name" => "Australian Dollar / Hong Kong Dollar", "category" => "EXOTICS"],
            ["symbol" => "AUDHUF", "name" => "Australian Dollar / Hungarian Forint", "category" => "EXOTICS"],
            ["symbol" => "AUDIDR", "name" => "Australian Dollar / Indonesian Rupiah", "category" => "EXOTICS"],
            ["symbol" => "AUDILS", "name" => "Australian Dollar / Israeli Shekel", "category" => "EXOTICS"],
            ["symbol" => "AUDINR", "name" => "Australian Dollar / Indian Rupee", "category" => "EXOTICS"],
            ["symbol" => "AUDJPY", "name" => "Australian Dollar / Japanese Yen", "category" => "MINORS"],
            ["symbol" => "AUDKRW", "name" => "Australian Dollar / South Korean Won", "category" => "EXOTICS"],
            ["symbol" => "AUDMXN", "name" => "Australian Dollar / Mexican Peso", "category" => "EXOTICS"],
            ["symbol" => "AUDMYR", "name" => "Australian Dollar / Malaysian Ringgit", "category" => "EXOTICS"],
            ["symbol" => "AUDNOK", "name" => "Australian Dollar / Norwegian Krone", "category" => "EXOTICS"],
            ["symbol" => "AUDNZD", "name" => "Australian Dollar / New Zealand Dollar", "category" => "MINORS"],
            ["symbol" => "AUDPLN", "name" => "Australian Dollar / Polish Zloty", "category" => "EXOTICS"],
            ["symbol" => "AUDSEK", "name" => "Australian Dollar / Swedish Krona", "category" => "EXOTICS"],
            ["symbol" => "AUDSGD", "name" => "Australian Dollar / Singapore Dollar", "category" => "EXOTICS"],
            ["symbol" => "AUDTHB", "name" => "Australian Dollar / Thai Baht", "category" => "EXOTICS"],
            ["symbol" => "AUDTRY", "name" => "Australian Dollar / Turkish Lira", "category" => "EXOTICS"],
            ["symbol" => "AUDTWD", "name" => "Australian Dollar / Taiwan Dollar", "category" => "EXOTICS"],
            ["symbol" => "AUDUSD", "name" => "Australian Dollar / US Dollar", "category" => "MAJORS"],
            ["symbol" => "AUDZAR", "name" => "Australian Dollar / South African Rand", "category" => "EXOTICS"],
            ["symbol" => "AVAXUSD", "name" => "Avalanche / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "AXSUSD", "name" => "Axie Infinity / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "BCHUSD", "name" => "Bitcoin Cash / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "BNBBTC", "name" => "BNB / Bitcoin", "category" => "CRYPTO"],
            ["symbol" => "BNBEUR", "name" => "BNB / Euro", "category" => "CRYPTO"],
            ["symbol" => "BNBUSD", "name" => "BNB / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "BONKUSD", "name" => "Bonk / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "BTCEUR", "name" => "Bitcoin / Euro", "category" => "CRYPTO"],
            ["symbol" => "BTCUSD", "name" => "Bitcoin / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "CADCHF", "name" => "Canadian Dollar / Swiss Franc", "category" => "MINORS"],
            ["symbol" => "CADDKK", "name" => "Canadian Dollar / Danish Krone", "category" => "EXOTICS"],
            ["symbol" => "CADEUR", "name" => "Canadian Dollar / Euro", "category" => "MINORS"],
            ["symbol" => "CADGBP", "name" => "Canadian Dollar / British Pound", "category" => "MINORS"],
            ["symbol" => "CADHKD", "name" => "Canadian Dollar / Hong Kong Dollar", "category" => "EXOTICS"],
            ["symbol" => "CADILS", "name" => "Canadian Dollar / Israeli Shekel", "category" => "EXOTICS"],
            ["symbol" => "CADINR", "name" => "Canadian Dollar / Indian Rupee", "category" => "EXOTICS"],
            ["symbol" => "CADJPY", "name" => "Canadian Dollar / Japanese Yen", "category" => "MINORS"],
            ["symbol" => "CADMXN", "name" => "Canadian Dollar / Mexican Peso", "category" => "EXOTICS"],
            ["symbol" => "CADNOK", "name" => "Canadian Dollar / Norwegian Krone", "category" => "EXOTICS"],
            ["symbol" => "CADPLN", "name" => "Canadian Dollar / Polish Zloty", "category" => "EXOTICS"],
            ["symbol" => "CADSEK", "name" => "Canadian Dollar / Swedish Krona", "category" => "EXOTICS"],
            ["symbol" => "CADSGD", "name" => "Canadian Dollar / Singapore Dollar", "category" => "EXOTICS"],
            ["symbol" => "CADTRY", "name" => "Canadian Dollar / Turkish Lira", "category" => "EXOTICS"],
            ["symbol" => "CADZAR", "name" => "Canadian Dollar / South African Rand", "category" => "EXOTICS"],
            ["symbol" => "CHFCZK", "name" => "Swiss Franc / Czech Koruna", "category" => "EXOTICS"],
            ["symbol" => "CHFDKK", "name" => "Swiss Franc / Danish Krone", "category" => "EXOTICS"],
            ["symbol" => "CHFEUR", "name" => "Swiss Franc / Euro", "category" => "MINORS"],
            ["symbol" => "CHFGBP", "name" => "Swiss Franc / British Pound", "category" => "MINORS"],
            ["symbol" => "CHFHKD", "name" => "Swiss Franc / Hong Kong Dollar", "category" => "EXOTICS"],
            ["symbol" => "CHFHUF", "name" => "Swiss Franc / Hungarian Forint", "category" => "EXOTICS"],
            ["symbol" => "CHFINR", "name" => "Swiss Franc / Indian Rupee", "category" => "EXOTICS"],
            ["symbol" => "CHFJPY", "name" => "Swiss Franc / Japanese Yen", "category" => "MINORS"],
            ["symbol" => "CHFNOK", "name" => "Swiss Franc / Norwegian Krone", "category" => "EXOTICS"],
            ["symbol" => "CHFPLN", "name" => "Swiss Franc / Polish Zloty", "category" => "EXOTICS"],
            ["symbol" => "CHFRUB", "name" => "Swiss Franc / Russian Ruble", "category" => "EXOTICS"],
            ["symbol" => "CHFSEK", "name" => "Swiss Franc / Swedish Krona", "category" => "EXOTICS"],
            ["symbol" => "CHFSGD", "name" => "Swiss Franc / Singapore Dollar", "category" => "EXOTICS"],
            ["symbol" => "CHFTHB", "name" => "Swiss Franc / Thai Baht", "category" => "EXOTICS"],
            ["symbol" => "CHFTRY", "name" => "Swiss Franc / Turkish Lira", "category" => "EXOTICS"],
            ["symbol" => "CHFZAR", "name" => "Swiss Franc / South African Rand", "category" => "EXOTICS"],
            ["symbol" => "CNHHKD", "name" => "Chinese Yuan (Offshore) / Hong Kong Dollar", "category" => "EXOTICS"],
            ["symbol" => "CNHJPY", "name" => "Chinese Yuan (Offshore) / Japanese Yen", "category" => "EXOTICS"],
            ["symbol" => "COMPUSD", "name" => "Compound / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "CRVUSD", "name" => "Curve DAO Token / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "CZKJPY", "name" => "Czech Koruna / Japanese Yen", "category" => "EXOTICS"],
            ["symbol" => "DASHUSD", "name" => "Dash / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "DKKCHF", "name" => "Danish Krone / Swiss Franc", "category" => "EXOTICS"],
            ["symbol" => "DKKJPY", "name" => "Danish Krone / Japanese Yen", "category" => "EXOTICS"],
            ["symbol" => "DKKNOK", "name" => "Danish Krone / Norwegian Krone", "category" => "EXOTICS"],
            ["symbol" => "DKKSEK", "name" => "Danish Krone / Swedish Krona", "category" => "EXOTICS"],
            ["symbol" => "DOGEUSD", "name" => "Dogecoin / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "DOTUSD", "name" => "Polkadot / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "ENAUSD", "name" => "Ethena / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "ENJUSD", "name" => "Enjin Coin / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "ETCUSD", "name" => "Ethereum Classic / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "ETHBTC", "name" => "Ethereum / Bitcoin", "category" => "CRYPTO"],
            ["symbol" => "ETHEUR", "name" => "Ethereum / Euro", "category" => "CRYPTO"],
            ["symbol" => "ETHUSD", "name" => "Ethereum / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "EURAED", "name" => "Euro / UAE Dirham", "category" => "EXOTICS"],
            ["symbol" => "EURAUD", "name" => "Euro / Australian Dollar", "category" => "MINORS"],
            ["symbol" => "EURBRL", "name" => "Euro / Brazilian Real", "category" => "EXOTICS"],
            ["symbol" => "EURCAD", "name" => "Euro / Canadian Dollar", "category" => "MINORS"],
            ["symbol" => "EURCHF", "name" => "Euro / Swiss Franc", "category" => "MINORS"],
            ["symbol" => "EURCNH", "name" => "Euro / Chinese Yuan (Offshore)", "category" => "EXOTICS"],
            ["symbol" => "EURCZK", "name" => "Euro / Czech Koruna", "category" => "EXOTICS"],
            ["symbol" => "EURDKK", "name" => "Euro / Danish Krone", "category" => "EXOTICS"],
            ["symbol" => "EUREGP", "name" => "Euro / Egyptian Pound", "category" => "EXOTICS"],
            ["symbol" => "EURGBP", "name" => "Euro / British Pound", "category" => "MINORS"],
            ["symbol" => "EURHKD", "name" => "Euro / Hong Kong Dollar", "category" => "EXOTICS"],
            ["symbol" => "EURHUF", "name" => "Euro / Hungarian Forint", "category" => "EXOTICS"],
            ["symbol" => "EURIDR", "name" => "Euro / Indonesian Rupiah", "category" => "EXOTICS"],
            ["symbol" => "EURILS", "name" => "Euro / Israeli Shekel", "category" => "EXOTICS"],
            ["symbol" => "EURINR", "name" => "Euro / Indian Rupee", "category" => "EXOTICS"],
            ["symbol" => "EURJPY", "name" => "Euro / Japanese Yen", "category" => "MINORS"],
            ["symbol" => "EURKRW", "name" => "Euro / South Korean Won", "category" => "EXOTICS"],
            ["symbol" => "EURMXN", "name" => "Euro / Mexican Peso", "category" => "EXOTICS"],
            ["symbol" => "EURMYR", "name" => "Euro / Malaysian Ringgit", "category" => "EXOTICS"],
            ["symbol" => "EURNOK", "name" => "Euro / Norwegian Krone", "category" => "EXOTICS"],
            ["symbol" => "EURNZD", "name" => "Euro / New Zealand Dollar", "category" => "MINORS"],
            ["symbol" => "EURPHP", "name" => "Euro / Philippine Peso", "category" => "EXOTICS"],
            ["symbol" => "EURPLN", "name" => "Euro / Polish Zloty", "category" => "EXOTICS"],
            ["symbol" => "EURRON", "name" => "Euro / Romanian Leu", "category" => "EXOTICS"],
            ["symbol" => "EURRUB", "name" => "Euro / Russian Ruble", "category" => "EXOTICS"],
            ["symbol" => "EURSAR", "name" => "Euro / Saudi Riyal", "category" => "EXOTICS"],
            ["symbol" => "EURSEK", "name" => "Euro / Swedish Krona", "category" => "EXOTICS"],
            ["symbol" => "EURSGD", "name" => "Euro / Singapore Dollar", "category" => "EXOTICS"],
            ["symbol" => "EURTHB", "name" => "Euro / Thai Baht", "category" => "EXOTICS"],
            ["symbol" => "EURTRY", "name" => "Euro / Turkish Lira", "category" => "EXOTICS"],
            ["symbol" => "EURTWD", "name" => "Euro / Taiwan Dollar", "category" => "EXOTICS"],
            ["symbol" => "EURUSD", "name" => "Euro / US Dollar", "category" => "MAJORS"],
            ["symbol" => "EURZAR", "name" => "Euro / South African Rand", "category" => "EXOTICS"],
            ["symbol" => "FETUSD", "name" => "Fetch.ai / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "FILUSD", "name" => "Filecoin / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "FLOKIUSD", "name" => "Floki / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "FLOWUSD", "name" => "Flow / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "GALAUSD", "name" => "Gala / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "GBPAED", "name" => "British Pound / UAE Dirham", "category" => "EXOTICS"],
            ["symbol" => "GBPAUD", "name" => "British Pound / Australian Dollar", "category" => "MINORS"],
            ["symbol" => "GBPBRL", "name" => "British Pound / Brazilian Real", "category" => "EXOTICS"],
            ["symbol" => "GBPCAD", "name" => "British Pound / Canadian Dollar", "category" => "MINORS"],
            ["symbol" => "GBPCHF", "name" => "British Pound / Swiss Franc", "category" => "MINORS"],
            ["symbol" => "GBPCNH", "name" => "British Pound / Chinese Yuan (Offshore)", "category" => "EXOTICS"],
            ["symbol" => "GBPCZK", "name" => "British Pound / Czech Koruna", "category" => "EXOTICS"],
            ["symbol" => "GBPDKK", "name" => "British Pound / Danish Krone", "category" => "EXOTICS"],
            ["symbol" => "GBPEUR", "name" => "British Pound / Euro", "category" => "MINORS"],
            ["symbol" => "GBPHKD", "name" => "British Pound / Hong Kong Dollar", "category" => "EXOTICS"],
            ["symbol" => "GBPHUF", "name" => "British Pound / Hungarian Forint", "category" => "EXOTICS"],
            ["symbol" => "GBPIDR", "name" => "British Pound / Indonesian Rupiah", "category" => "EXOTICS"],
            ["symbol" => "GBPILS", "name" => "British Pound / Israeli Shekel", "category" => "EXOTICS"],
            ["symbol" => "GBPINR", "name" => "British Pound / Indian Rupee", "category" => "EXOTICS"],
            ["symbol" => "GBPJPY", "name" => "British Pound / Japanese Yen", "category" => "MINORS"],
            ["symbol" => "GBPKRW", "name" => "British Pound / South Korean Won", "category" => "EXOTICS"],
            ["symbol" => "GBPMXN", "name" => "British Pound / Mexican Peso", "category" => "EXOTICS"],
            ["symbol" => "GBPMYR", "name" => "British Pound / Malaysian Ringgit", "category" => "EXOTICS"],
            ["symbol" => "GBPNOK", "name" => "British Pound / Norwegian Krone", "category" => "EXOTICS"],
            ["symbol" => "GBPNZD", "name" => "British Pound / New Zealand Dollar", "category" => "MINORS"],
            ["symbol" => "GBPPHP", "name" => "British Pound / Philippine Peso", "category" => "EXOTICS"],
            ["symbol" => "GBPPLN", "name" => "British Pound / Polish Zloty", "category" => "EXOTICS"],
            ["symbol" => "GBPRON", "name" => "British Pound / Romanian Leu", "category" => "EXOTICS"],
            ["symbol" => "GBPRUB", "name" => "British Pound / Russian Ruble", "category" => "EXOTICS"],
            ["symbol" => "GBPSAR", "name" => "British Pound / Saudi Riyal", "category" => "EXOTICS"],
            ["symbol" => "GBPSEK", "name" => "British Pound / Swedish Krona", "category" => "EXOTICS"],
            ["symbol" => "GBPSGD", "name" => "British Pound / Singapore Dollar", "category" => "EXOTICS"],
            ["symbol" => "GBPTHB", "name" => "British Pound / Thai Baht", "category" => "EXOTICS"],
            ["symbol" => "GBPTRY", "name" => "British Pound / Turkish Lira", "category" => "EXOTICS"],
            ["symbol" => "GBPTWD", "name" => "British Pound / Taiwan Dollar", "category" => "EXOTICS"],
            ["symbol" => "GBPUSD", "name" => "British Pound / US Dollar", "category" => "MAJORS"],
            ["symbol" => "GBPZAR", "name" => "British Pound / South African Rand", "category" => "EXOTICS"],
            ["symbol" => "GRTUSD", "name" => "The Graph / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "HBARUSD", "name" => "Hedera / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "HKDJPY", "name" => "Hong Kong Dollar / Japanese Yen", "category" => "EXOTICS"],
            ["symbol" => "HUFCHF", "name" => "Hungarian Forint / Swiss Franc", "category" => "EXOTICS"],
            ["symbol" => "ICPUSD", "name" => "Internet Computer / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "ILSJPY", "name" => "Israeli Shekel / Japanese Yen", "category" => "EXOTICS"],
            ["symbol" => "IMXUSD", "name" => "Immutable X / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "INJUSD", "name" => "Injective / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "INRJPY", "name" => "Indian Rupee / Japanese Yen", "category" => "EXOTICS"],
            ["symbol" => "JPYAUD", "name" => "Japanese Yen / Australian Dollar", "category" => "MINORS"],
            ["symbol" => "JPYBRL", "name" => "Japanese Yen / Brazilian Real", "category" => "EXOTICS"],
            ["symbol" => "JPYCAD", "name" => "Japanese Yen / Canadian Dollar", "category" => "MINORS"],
            ["symbol" => "JPYCHF", "name" => "Japanese Yen / Swiss Franc", "category" => "MINORS"],
            ["symbol" => "JPYCZK", "name" => "Japanese Yen / Czech Koruna", "category" => "EXOTICS"],
            ["symbol" => "JPYDKK", "name" => "Japanese Yen / Danish Krone", "category" => "EXOTICS"],
            ["symbol" => "JPYEUR", "name" => "Japanese Yen / Euro", "category" => "MINORS"],
            ["symbol" => "JPYGBP", "name" => "Japanese Yen / British Pound", "category" => "MINORS"],
            ["symbol" => "JPYHKD", "name" => "Japanese Yen / Hong Kong Dollar", "category" => "EXOTICS"],
            ["symbol" => "JPYIDR", "name" => "Japanese Yen / Indonesian Rupiah", "category" => "EXOTICS"],
            ["symbol" => "JPYILS", "name" => "Japanese Yen / Israeli Shekel", "category" => "EXOTICS"],
            ["symbol" => "JPYINR", "name" => "Japanese Yen / Indian Rupee", "category" => "EXOTICS"],
            ["symbol" => "JPYKRW", "name" => "Japanese Yen / South Korean Won", "category" => "EXOTICS"],
            ["symbol" => "JPYMXN", "name" => "Japanese Yen / Mexican Peso", "category" => "EXOTICS"],
            ["symbol" => "JPYMYR", "name" => "Japanese Yen / Malaysian Ringgit", "category" => "EXOTICS"],
            ["symbol" => "JPYNOK", "name" => "Japanese Yen / Norwegian Krone", "category" => "EXOTICS"],
            ["symbol" => "JPYNZD", "name" => "Japanese Yen / New Zealand Dollar", "category" => "MINORS"],
            ["symbol" => "JPYPLN", "name" => "Japanese Yen / Polish Zloty", "category" => "EXOTICS"],
            ["symbol" => "JPYRUB", "name" => "Japanese Yen / Russian Ruble", "category" => "EXOTICS"],
            ["symbol" => "JPYSEK", "name" => "Japanese Yen / Swedish Krona", "category" => "EXOTICS"],
            ["symbol" => "JPYTHB", "name" => "Japanese Yen / Thai Baht", "category" => "EXOTICS"],
            ["symbol" => "JPYTWD", "name" => "Japanese Yen / Taiwan Dollar", "category" => "EXOTICS"],
            ["symbol" => "JPYZAR", "name" => "Japanese Yen / South African Rand", "category" => "EXOTICS"],
            ["symbol" => "JUPUSD", "name" => "Jupiter / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "LDOUSD", "name" => "Lido DAO / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "LINKUSD", "name" => "Chainlink / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "LTCBTC", "name" => "Litecoin / Bitcoin", "category" => "CRYPTO"],
            ["symbol" => "LTCEUR", "name" => "Litecoin / Euro", "category" => "CRYPTO"],
            ["symbol" => "LTCUSD", "name" => "Litecoin / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "MANAUSD", "name" => "Decentraland / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "MXNJPY", "name" => "Mexican Peso / Japanese Yen", "category" => "EXOTICS"],
            ["symbol" => "NEARUSD", "name" => "NEAR Protocol / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "NEOUSD", "name" => "NEO / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "NOKCHF", "name" => "Norwegian Krone / Swiss Franc", "category" => "EXOTICS"],
            ["symbol" => "NOKDKK", "name" => "Norwegian Krone / Danish Krone", "category" => "EXOTICS"],
            ["symbol" => "NOKJPY", "name" => "Norwegian Krone / Japanese Yen", "category" => "EXOTICS"],
            ["symbol" => "NOKSEK", "name" => "Norwegian Krone / Swedish Krona", "category" => "EXOTICS"],
            ["symbol" => "NZDAUD", "name" => "New Zealand Dollar / Australian Dollar", "category" => "MINORS"],
            ["symbol" => "NZDCAD", "name" => "New Zealand Dollar / Canadian Dollar", "category" => "MINORS"],
            ["symbol" => "NZDCHF", "name" => "New Zealand Dollar / Swiss Franc", "category" => "MINORS"],
            ["symbol" => "NZDDKK", "name" => "New Zealand Dollar / Danish Krone", "category" => "EXOTICS"],
            ["symbol" => "NZDEUR", "name" => "New Zealand Dollar / Euro", "category" => "MINORS"],
            ["symbol" => "NZDGBP", "name" => "New Zealand Dollar / British Pound", "category" => "MINORS"],
            ["symbol" => "NZDJPY", "name" => "New Zealand Dollar / Japanese Yen", "category" => "MINORS"],
            ["symbol" => "NZDNOK", "name" => "New Zealand Dollar / Norwegian Krone", "category" => "EXOTICS"],
            ["symbol" => "NZDSEK", "name" => "New Zealand Dollar / Swedish Krona", "category" => "EXOTICS"],
            ["symbol" => "NZDSGD", "name" => "New Zealand Dollar / Singapore Dollar", "category" => "EXOTICS"],
            ["symbol" => "NZDTRY", "name" => "New Zealand Dollar / Turkish Lira", "category" => "EXOTICS"],
            ["symbol" => "NZDUSD", "name" => "New Zealand Dollar / US Dollar", "category" => "MAJORS"],
            ["symbol" => "NZDZAR", "name" => "New Zealand Dollar / South African Rand", "category" => "EXOTICS"],
            ["symbol" => "ONDOUSD", "name" => "Ondo / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "OPUSD", "name" => "Optimism / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "PENGUUSD", "name" => "Pudgy Penguins / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "PEPEUSD", "name" => "Pepe / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "PLNCHF", "name" => "Polish Zloty / Swiss Franc", "category" => "EXOTICS"],
            ["symbol" => "PLNJPY", "name" => "Polish Zloty / Japanese Yen", "category" => "EXOTICS"],
            ["symbol" => "QNTUSD", "name" => "Quant / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "RENDERUSD", "name" => "Render / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "RUNEUSD", "name" => "THORChain / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "SANDUSD", "name" => "The Sandbox / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "SEIUSD", "name" => "Sei / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "SEKCHF", "name" => "Swedish Krona / Swiss Franc", "category" => "EXOTICS"],
            ["symbol" => "SEKJPY", "name" => "Swedish Krona / Japanese Yen", "category" => "EXOTICS"],
            ["symbol" => "SEKNOK", "name" => "Swedish Krona / Norwegian Krone", "category" => "EXOTICS"],
            ["symbol" => "SGDCHF", "name" => "Singapore Dollar / Swiss Franc", "category" => "EXOTICS"],
            ["symbol" => "SGDJPY", "name" => "Singapore Dollar / Japanese Yen", "category" => "EXOTICS"],
            ["symbol" => "SHIBUSD", "name" => "Shiba Inu / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "SNXUSD", "name" => "Synthetix / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "SOLBTC", "name" => "Solana / Bitcoin", "category" => "CRYPTO"],
            ["symbol" => "SOLEUR", "name" => "Solana / Euro", "category" => "CRYPTO"],
            ["symbol" => "SOLUSD", "name" => "Solana / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "STXUSD", "name" => "Stacks / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "SUIUSD", "name" => "Sui / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "TAOUSD", "name" => "Bittensor / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "THETAUSD", "name" => "Theta Network / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "TIAUSD", "name" => "Celestia / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "TRUMPUSD", "name" => "Official Trump / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "TRXUSD", "name" => "TRON / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "TRYCHF", "name" => "Turkish Lira / Swiss Franc", "category" => "EXOTICS"],
            ["symbol" => "TRYJPY", "name" => "Turkish Lira / Japanese Yen", "category" => "EXOTICS"],
            ["symbol" => "TRYZAR", "name" => "Turkish Lira / South African Rand", "category" => "EXOTICS"],
            ["symbol" => "UNIUSD", "name" => "Uniswap / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "USDAED", "name" => "US Dollar / UAE Dirham", "category" => "EXOTICS"],
            ["symbol" => "USDARS", "name" => "US Dollar / Argentine Peso", "category" => "EXOTICS"],
            ["symbol" => "USDAUD", "name" => "US Dollar / Australian Dollar", "category" => "MAJORS"],
            ["symbol" => "USDBRL", "name" => "US Dollar / Brazilian Real", "category" => "EXOTICS"],
            ["symbol" => "USDCAD", "name" => "US Dollar / Canadian Dollar", "category" => "MAJORS"],
            ["symbol" => "USDCHF", "name" => "US Dollar / Swiss Franc", "category" => "MAJORS"],
            ["symbol" => "USDCLP", "name" => "US Dollar / Chilean Peso", "category" => "EXOTICS"],
            ["symbol" => "USDCNH", "name" => "US Dollar / Chinese Yuan (Offshore)", "category" => "EXOTICS"],
            ["symbol" => "USDCOP", "name" => "US Dollar / Colombian Peso", "category" => "EXOTICS"],
            ["symbol" => "USDCZK", "name" => "US Dollar / Czech Koruna", "category" => "EXOTICS"],
            ["symbol" => "USDDKK", "name" => "US Dollar / Danish Krone", "category" => "EXOTICS"],
            ["symbol" => "USDEGP", "name" => "US Dollar / Egyptian Pound", "category" => "EXOTICS"],
            ["symbol" => "USDEUR", "name" => "US Dollar / Euro", "category" => "MAJORS"],
            ["symbol" => "USDGBP", "name" => "US Dollar / British Pound", "category" => "MAJORS"],
            ["symbol" => "USDHKD", "name" => "US Dollar / Hong Kong Dollar", "category" => "EXOTICS"],
            ["symbol" => "USDHUF", "name" => "US Dollar / Hungarian Forint", "category" => "EXOTICS"],
            ["symbol" => "USDIDR", "name" => "US Dollar / Indonesian Rupiah", "category" => "EXOTICS"],
            ["symbol" => "USDILS", "name" => "US Dollar / Israeli Shekel", "category" => "EXOTICS"],
            ["symbol" => "USDINR", "name" => "US Dollar / Indian Rupee", "category" => "EXOTICS"],
            ["symbol" => "USDISK", "name" => "US Dollar / Icelandic Krona", "category" => "EXOTICS"],
            ["symbol" => "USDJPY", "name" => "US Dollar / Japanese Yen", "category" => "MAJORS"],
            ["symbol" => "USDKRW", "name" => "US Dollar / South Korean Won", "category" => "EXOTICS"],
            ["symbol" => "USDMXN", "name" => "US Dollar / Mexican Peso", "category" => "EXOTICS"],
            ["symbol" => "USDMYR", "name" => "US Dollar / Malaysian Ringgit", "category" => "EXOTICS"],
            ["symbol" => "USDNOK", "name" => "US Dollar / Norwegian Krone", "category" => "EXOTICS"],
            ["symbol" => "USDNZD", "name" => "US Dollar / New Zealand Dollar", "category" => "MAJORS"],
            ["symbol" => "USDPEN", "name" => "US Dollar / Peruvian Sol", "category" => "EXOTICS"],
            ["symbol" => "USDPHP", "name" => "US Dollar / Philippine Peso", "category" => "EXOTICS"],
            ["symbol" => "USDPKR", "name" => "US Dollar / Pakistani Rupee", "category" => "EXOTICS"],
            ["symbol" => "USDPLN", "name" => "US Dollar / Polish Zloty", "category" => "EXOTICS"],
            ["symbol" => "USDRON", "name" => "US Dollar / Romanian Leu", "category" => "EXOTICS"],
            ["symbol" => "USDRUB", "name" => "US Dollar / Russian Ruble", "category" => "EXOTICS"],
            ["symbol" => "USDSAR", "name" => "US Dollar / Saudi Riyal", "category" => "EXOTICS"],
            ["symbol" => "USDSEK", "name" => "US Dollar / Swedish Krona", "category" => "EXOTICS"],
            ["symbol" => "USDSGD", "name" => "US Dollar / Singapore Dollar", "category" => "EXOTICS"],
            ["symbol" => "USDTHB", "name" => "US Dollar / Thai Baht", "category" => "EXOTICS"],
            ["symbol" => "USDTRY", "name" => "US Dollar / Turkish Lira", "category" => "EXOTICS"],
            ["symbol" => "USDTWD", "name" => "US Dollar / Taiwan Dollar", "category" => "EXOTICS"],
            ["symbol" => "USDVND", "name" => "US Dollar / Vietnamese Dong", "category" => "EXOTICS"],
            ["symbol" => "USDZAR", "name" => "US Dollar / South African Rand", "category" => "EXOTICS"],
            ["symbol" => "VETUSD", "name" => "VeChain / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "VIRTUALUSD", "name" => "Virtuals Protocol / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "WIFUSD", "name" => "dogwifhat / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "WLDUSD", "name" => "Worldcoin / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "XAGAUD", "name" => "Silver / Australian Dollar", "category" => "METALS"],
            ["symbol" => "XAGCAD", "name" => "Silver / Canadian Dollar", "category" => "METALS"],
            ["symbol" => "XAGEUR", "name" => "Silver / Euro", "category" => "METALS"],
            ["symbol" => "XAGGBP", "name" => "Silver / British Pound", "category" => "METALS"],
            ["symbol" => "XAGINR", "name" => "Silver / Indian Rupee", "category" => "METALS"],
            ["symbol" => "XAGJPY", "name" => "Silver / Japanese Yen", "category" => "METALS"],
            ["symbol" => "XAGSAR", "name" => "Silver / Saudi Riyal", "category" => "METALS"],
            ["symbol" => "XAGTRY", "name" => "Silver / Turkish Lira", "category" => "METALS"],
            ["symbol" => "XAGUSD", "name" => "Silver / US Dollar", "category" => "METALS"],
            ["symbol" => "XAGZAR", "name" => "Silver / South African Rand", "category" => "METALS"],
            ["symbol" => "XAUAUD", "name" => "Gold / Australian Dollar", "category" => "METALS"],
            ["symbol" => "XAUCAD", "name" => "Gold / Canadian Dollar", "category" => "METALS"],
            ["symbol" => "XAUEUR", "name" => "Gold / Euro", "category" => "METALS"],
            ["symbol" => "XAUGBP", "name" => "Gold / British Pound", "category" => "METALS"],
            ["symbol" => "XAUINR", "name" => "Gold / Indian Rupee", "category" => "METALS"],
            ["symbol" => "XAUJPY", "name" => "Gold / Japanese Yen", "category" => "METALS"],
            ["symbol" => "XAUSAR", "name" => "Gold / Saudi Riyal", "category" => "METALS"],
            ["symbol" => "XAUUSD", "name" => "Gold / US Dollar", "category" => "METALS"],
            ["symbol" => "XAUZAR", "name" => "Gold / South African Rand", "category" => "METALS"],
            ["symbol" => "XLMUSD", "name" => "Stellar / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "XRPBTC", "name" => "XRP / Bitcoin", "category" => "CRYPTO"],
            ["symbol" => "XRPEUR", "name" => "XRP / Euro", "category" => "CRYPTO"],
            ["symbol" => "XRPUSD", "name" => "XRP / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "XTZUSD", "name" => "Tezos / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "ZARCHF", "name" => "South African Rand / Swiss Franc", "category" => "EXOTICS"],
            ["symbol" => "ZARJPY", "name" => "South African Rand / Japanese Yen", "category" => "EXOTICS"],
            ["symbol" => "ZECUSD", "name" => "Zcash / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "ZILUSD", "name" => "Zilliqa / US Dollar", "category" => "CRYPTO"],
            ["symbol" => "ZROUSD", "name" => "LayerZero / US Dollar", "category" => "CRYPTO"],
    ];

    public function up(): void
    {
        $canonicalSymbols = array_column(self::CATALOG, 'symbol');

        DB::table('assets')
            ->whereNull('deleted_at')
            ->whereNotIn('symbol', $canonicalSymbols)
            ->update(['deleted_at' => now()]);

        foreach (self::CATALOG as $entry) {
            DB::table('assets')
                ->where('symbol', $entry['symbol'])
                ->whereNull('deleted_at')
                ->update([
                    'name' => $entry['name'],
                    'asset_group' => $entry['category'],
                    'price_source' => 'brokeret',
                    'is_active' => true,
                    'updated_at' => now(),
                ]);
        }
    }

    /**
     * Restores whatever this migration soft-deleted and reverts names/groups
     * to the bare-symbol convention the previous seeder used. Doesn't attempt
     * to recall each row's pre-migration asset_group/name individually —
     * this is a best-effort rollback, not a perfect inverse.
     */
    public function down(): void
    {
        $canonicalSymbols = array_column(self::CATALOG, 'symbol');

        DB::table('assets')
            ->whereNotIn('symbol', $canonicalSymbols)
            ->whereNotNull('deleted_at')
            ->update(['deleted_at' => null]);
    }
};
